version: '3.8'

services:
  sso-app:
    image: projeto-arquitetura/sso-app-1.0.0
    container_name: sso-app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - arquitetura-network
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=${VIRTUAL_PORT}
      - VIRTUAL_DOMAIN=${VIRTUAL_DOMAIN}
    hostname: sso-app.lucaslabs.com
    restart: unless-stopped
    volumes:
      - D:/Projetos/Docker/Projeto Arquitetura/certificados/.lucaslabs:/certs
    entrypoint: ["/init.sh"]

networks:
  arquitetura-network:
    external: true
